# Generated by Django 3.2 on 2021-07-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechBlog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('subtitle', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='blog.BlogCategory')),
            ],
        ),
    ]
