# Generated by Django 3.2 on 2021-07-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techblog',
            name='category',
            field=models.ManyToManyField(blank=True, to='blog.BlogCategory'),
        ),
        migrations.AlterField(
            model_name='techblog',
            name='publish',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
