# Generated by Django 3.2 on 2021-07-18 14:28

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210711_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techblog',
            name='id',
            field=models.CharField(default=blog.models.random_code, max_length=6, primary_key=True, serialize=False),
        ),
    ]
