# Generated by Django 3.2 on 2021-07-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_techblog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techblog',
            old_name='category',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
