# Generated by Django 3.2 on 2021-08-01 14:15

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210718_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='techblog',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='techblog',
            name='id',
            field=models.CharField(auto_created=True, default=blog.models.random_code, max_length=6, primary_key=True, serialize=False),
        ),
    ]
